apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: novdan-api-generate-monthly-tokens
spec:
  schedule: "1 0 1 * *" # At 00:01 on day-of-month 1.
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: novdan-api-generate-monthly-tokens
              image: novdan-api
              command:
                - python
                - manage.py
                - generate_monthly_tokens
              envFrom:
                - secretRef:
                    name: novdan-api-secrets
              env:
                - name: DJANGO_SETTINGS_MODULE
                  value: novdan_api.settings.k8s
