apiVersion: apps/v1
kind: Deployment
metadata:
  name: novdan-api
  labels:
    app: novdan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novdan-api
  template:
    metadata:
      labels:
        app: novdan-api
    spec:
      initContainers:
        - name: collectstatic
          image: novdan-api
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          envFrom:
            - secretRef:
                name: novdan-secrets
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: novdan_api.settings.k8s
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 400Mi
              cpu: 200m
        - name: migrate
          image: novdan-api
          command:
            - python
            - manage.py
            - migrate
          envFrom:
            - secretRef:
                name: novdan-secrets
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: novdan_api.settings.k8s
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 400Mi
              cpu: 200m
      containers:
        - name: novdan-api
          image: novdan-api
          command:
            - gunicorn
            - novdan_api.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "30"
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: novdan-secrets
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: novdan_api.settings.k8s
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 400Mi
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: novdan-api
spec:
  selector:
    app: novdan-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novdan-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - api.novdan.lb.djnd.si
      secretName: novdan-api-tls
  rules:
    - host: api.novdan.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: novdan-api
                port:
                  number: 8000
