apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: novdan
resources:
  - frontend.yaml
  - api.yaml
  - cronjobs/api_generate_monthly_tokens.yaml
  - cronjobs/parse_articles.yaml
images:
  - name: novdan-frontend
    newName: rg.fr-par.scw.cloud/djnd/novdan-frontend
    newTag: 'f15704d52c2ec720c117e73c702ca71198a1fea0'
  - name: novdan-api
    newName: rg.fr-par.scw.cloud/djnd/novdan-api
    newTag: 'f15704d52c2ec720c117e73c702ca71198a1fea0'
