apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: novdan
resources:
  - frontend.yaml
  - api.yaml
  - cronjobs/api_generate_monthly_tokens.yaml
  - cronjobs/parse_articles.yaml
images:
  - name: novdan-frontend
    newName: rg.fr-par.scw.cloud/djnd/novdan-frontend
    newTag: 'fd3f7d97a1e94e4ed5ca9412d8abbc80330cf39d'
  - name: novdan-api
    newName: rg.fr-par.scw.cloud/djnd/novdan-api
    newTag: 'fd3f7d97a1e94e4ed5ca9412d8abbc80330cf39d'
