apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: novdan
resources:
  - frontend.yaml
  - api.yaml
  - cronjobs/api_generate_monthly_tokens.yaml
  - cronjobs/parse_articles.yaml
images:
  - name: novdan-frontend
    newName: rg.fr-par.scw.cloud/djnd/novdan-frontend
    newTag: '65b0611d09100e8408f90eb7092d90e093b3511f'
  - name: novdan-api
    newName: rg.fr-par.scw.cloud/djnd/novdan-api
    newTag: '65b0611d09100e8408f90eb7092d90e093b3511f'
