# Generated by Django 3.2.8 on 2021-10-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiontimerange',
            old_name='ended_at',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='subscriptiontimerange',
            old_name='started_at',
            new_name='start_at',
        ),
    ]
