# Generated by Django 3.2.8 on 2022-01-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211028_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiontimerange',
            old_name='payment_id',
            new_name='payment_token',
        ),
        migrations.AlterField(
            model_name='subscriptiontimerange',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_ranges', related_query_name='time_range', to='api.subscription'),
        ),
    ]
