# Generated by Django 3.2.8 on 2022-03-03 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontimerange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
