# Generated by Django 3.2.8 on 2023-12-17 20:28

from django.db import migrations


def populate_media(apps, schema_editor):
    Medium = apps.get_model("articles", "Medium")

    Medium.objects.bulk_create(
        [
            Medium(
                name="In media res (Vezjak)",
                url="https://vezjak.com/",
                article_rss_urls="https://vezjak.com/feed/",
            ),
            Medium(
                name="Oštro",
                url="https://www.ostro.si/",
                article_rss_urls="""https://www.ostro.si/si/zgodbe?format=rss
https://www.ostro.si/si/razkrinkavanje/objave?format=rss
https://www.ostro.si/si/komentarji?format=rss
https://www.ostro.si/si/novice?format=rss
""",
            ),
            Medium(
                name="Mešanec",
                url="https://mesanec.si/",
                article_rss_urls="https://mesanec.si/feed/",
            ),
            Medium(
                name="Agrument (Danes je nov dan)",
                url="https://danesjenovdan.si/agrument",
                article_rss_urls="https://agrument.danesjenovdan.si/rss/",
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_media, migrations.RunPython.noop),
    ]
