# Generated by Django 3.2.8 on 2023-12-17 22:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_populate_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('guid', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.medium')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
