# Generated by Django 3.2.8 on 2023-12-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20231217_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='article_css_selector',
        ),
        migrations.AddField(
            model_name='medium',
            name='image_css_selector',
            field=models.CharField(default='article img', max_length=256),
        ),
    ]
