# Generated by Django 3.2.8 on 2024-02-13 16:01

from django.db import migrations, models

import articles.models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_auto_20231217_2337"),
    ]

    operations = [
        migrations.AddField(
            model_name="medium",
            name="favicon",
            field=models.ImageField(
                blank=True, null=True, upload_to=articles.models.media_favicon_path
            ),
        ),
    ]
