# Generated by Django 3.2.8 on 2025-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_medium_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='slug',
            field=models.SlugField(max_length=64, null=True, unique=True),
        ),
    ]
