# Generated by Django 3.2.8 on 2025-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_medium_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='donation_campaign_slug',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
