# Generated by Django 3.2.8 on 2026-01-22 19:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_medium_donation_campaign_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediumLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "medium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_links",
                        to="articles.medium",
                    ),
                ),
            ],
        ),
    ]
