# Generated by Django 3.2.8 on 2026-01-23 11:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_mediumlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediumDonationAmount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="For custom amount use -1",
                        max_digits=10,
                    ),
                ),
                ("one_time", models.BooleanField(default=True)),
                ("recurring", models.BooleanField(default=True)),
                (
                    "medium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_amounts",
                        to="articles.medium",
                    ),
                ),
            ],
        ),
    ]
