# Generated by Django 3.2.8 on 2026-02-06 12:55

from django.db import migrations, models

import articles.models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_mediumdonationamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediumdonationamount",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=articles.models.media_amount_image_path
            ),
        ),
    ]
